"""Redesign DB schema for One-Stop AI

Revision ID: 8240304baa99
Revises: dbc818531f9b
Create Date: 2026-06-29 15:51:46.344038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8240304baa99'
down_revision: Union[str, Sequence[str], None] = 'dbc818531f9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_activity',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('activity_date', sa.Date(), nullable=False),
    sa.Column('problems_solved', sa.Integer(), nullable=False),
    sa.Column('problems_attempted', sa.Integer(), nullable=False),
    sa.Column('submissions_count', sa.Integer(), nullable=False),
    sa.Column('interviews_done', sa.Integer(), nullable=False),
    sa.Column('study_minutes', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'activity_date', name='uix_daily_activity_user_date')
    )
    op.create_index('idx_daily_activity_user_date', 'daily_activity', ['user_id', 'activity_date'], unique=False)
    op.create_table('user_skill_scores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(length=50), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('problems_solved', sa.Integer(), nullable=False),
    sa.Column('interviews_done', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'domain', name='uix_user_skill_scores_user_id_domain')
    )
    op.create_index('idx_skill_scores_user', 'user_skill_scores', ['user_id'], unique=False)
    op.create_table('user_stats',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('problems_solved_total', sa.Integer(), nullable=False),
    sa.Column('problems_solved_easy', sa.Integer(), nullable=False),
    sa.Column('problems_solved_medium', sa.Integer(), nullable=False),
    sa.Column('problems_solved_hard', sa.Integer(), nullable=False),
    sa.Column('total_submissions', sa.Integer(), nullable=False),
    sa.Column('acceptance_rate', sa.Float(), nullable=False),
    sa.Column('interviews_completed', sa.Integer(), nullable=False),
    sa.Column('avg_interview_score', sa.Float(), nullable=False),
    sa.Column('best_interview_score', sa.Integer(), nullable=False),
    sa.Column('current_streak', sa.Integer(), nullable=False),
    sa.Column('longest_streak', sa.Integer(), nullable=False),
    sa.Column('last_activity_date', sa.Date(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.drop_index(op.f('ix_schedule_tasks_schedule_id'), table_name='schedule_tasks')
    op.drop_table('schedule_tasks')
    op.drop_index(op.f('ix_schedules_user_id'), table_name='schedules')
    op.drop_table('schedules')
    op.drop_index(op.f('ix_user_roadmap_steps_user_roadmap_id'), table_name='user_roadmap_steps')
    op.drop_table('user_roadmap_steps')
    op.drop_index(op.f('ix_user_roadmaps_user_id'), table_name='user_roadmaps')
    op.drop_table('user_roadmaps')
    op.drop_index(op.f('ix_roadmap_steps_roadmap_id'), table_name='roadmap_steps')
    op.drop_table('roadmap_steps')
    op.drop_table('roadmaps')
    op.drop_table('user_streaks')
    op.drop_index(op.f('ix_user_skills_user_id'), table_name='user_skills')
    op.drop_table('user_skills')
    op.add_column('learning_events', sa.Column('domain', sa.String(length=50), nullable=True))
    op.add_column('learning_events', sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('user_profiles', sa.Column('headline', sa.String(length=200), nullable=True))
    op.add_column('user_profiles', sa.Column('location', sa.String(length=100), nullable=True))
    op.add_column('user_profiles', sa.Column('institution', sa.String(length=200), nullable=True))
    op.add_column('user_profiles', sa.Column('preferred_language', sa.String(length=20), nullable=True))
    op.add_column('user_profiles', sa.Column('resume_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'resume_url')
    op.drop_column('user_profiles', 'preferred_language')
    op.drop_column('user_profiles', 'institution')
    op.drop_column('user_profiles', 'location')
    op.drop_column('user_profiles', 'headline')
    op.drop_column('learning_events', 'metadata_json')
    op.drop_column('learning_events', 'domain')
    op.create_table('roadmap_steps',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('roadmap_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('order_index', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('reference_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['roadmap_id'], ['roadmaps.id'], name=op.f('roadmap_steps_roadmap_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('roadmap_steps_pkey'))
    )
    op.create_index(op.f('ix_roadmap_steps_roadmap_id'), 'roadmap_steps', ['roadmap_id'], unique=False)
    op.create_table('user_roadmaps',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('roadmap_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_completed', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['roadmap_id'], ['roadmaps.id'], name=op.f('user_roadmaps_roadmap_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_roadmaps_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('user_roadmaps_pkey'))
    )
    op.create_index(op.f('ix_user_roadmaps_user_id'), 'user_roadmaps', ['user_id'], unique=False)
    op.create_table('schedules',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('schedules_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('schedules_pkey'))
    )
    op.create_index(op.f('ix_schedules_user_id'), 'schedules', ['user_id'], unique=False)
    op.create_table('user_skills',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('domain', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('score', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_skills_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('user_skills_pkey')),
    sa.UniqueConstraint('user_id', 'domain', name=op.f('uix_user_id_domain'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_user_skills_user_id'), 'user_skills', ['user_id'], unique=False)
    op.create_table('user_roadmap_steps',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_roadmap_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('roadmap_step_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_completed', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['roadmap_step_id'], ['roadmap_steps.id'], name=op.f('user_roadmap_steps_roadmap_step_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_roadmap_id'], ['user_roadmaps.id'], name=op.f('user_roadmap_steps_user_roadmap_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('user_roadmap_steps_pkey'))
    )
    op.create_index(op.f('ix_user_roadmap_steps_user_roadmap_id'), 'user_roadmap_steps', ['user_roadmap_id'], unique=False)
    op.create_table('roadmaps',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('roadmaps_pkey'))
    )
    op.create_table('user_streaks',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('current_streak', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('longest_streak', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('last_activity_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_streaks_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('user_streaks_pkey')),
    sa.UniqueConstraint('user_id', name=op.f('user_streaks_user_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('schedule_tasks',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('schedule_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('due_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('is_completed', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedules.id'], name=op.f('schedule_tasks_schedule_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('schedule_tasks_pkey'))
    )
    op.create_index(op.f('ix_schedule_tasks_schedule_id'), 'schedule_tasks', ['schedule_id'], unique=False)
    op.drop_table('user_stats')
    op.drop_index('idx_skill_scores_user', table_name='user_skill_scores')
    op.drop_table('user_skill_scores')
    op.drop_index('idx_daily_activity_user_date', table_name='daily_activity')
    op.drop_table('daily_activity')
    # ### end Alembic commands ###
