"""add_missing_tables

Revision ID: dce905768024
Revises: d5fa44b949e1
Create Date: 2026-08-11 19:23:39.148989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dce905768024'
down_revision: Union[str, Sequence[str], None] = 'd5fa44b949e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aiml_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('domain', sa.String(length=100), nullable=True),
    sa.Column('role', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aiml_questions_id'), 'aiml_questions', ['id'], unique=False)
    op.create_table('behavioral_questions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_behavioral_questions_category'), 'behavioral_questions', ['category'], unique=False)
    op.create_index(op.f('ix_behavioral_questions_id'), 'behavioral_questions', ['id'], unique=False)
    op.create_index(op.f('ix_behavioral_questions_title'), 'behavioral_questions', ['title'], unique=False)
    op.create_table('daily_activity',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('activity_date', sa.Date(), nullable=False),
    sa.Column('problems_solved', sa.Integer(), nullable=False),
    sa.Column('problems_attempted', sa.Integer(), nullable=False),
    sa.Column('submissions_count', sa.Integer(), nullable=False),
    sa.Column('interviews_done', sa.Integer(), nullable=False),
    sa.Column('study_minutes', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_activity_user_id'), 'daily_activity', ['user_id'], unique=False)
    op.create_table('learning_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('reference_id', sa.String(), nullable=True),
    sa.Column('score_change', sa.Float(), nullable=False),
    sa.Column('domain', sa.String(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learning_events_event_type'), 'learning_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_learning_events_user_id'), 'learning_events', ['user_id'], unique=False)
    op.create_table('pm_questions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pm_questions_category'), 'pm_questions', ['category'], unique=False)
    op.create_index(op.f('ix_pm_questions_id'), 'pm_questions', ['id'], unique=False)
    op.create_index(op.f('ix_pm_questions_title'), 'pm_questions', ['title'], unique=False)
    op.create_table('user_skill_scores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('domain', sa.String(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('problems_solved', sa.Integer(), nullable=False),
    sa.Column('interviews_done', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_skill_scores_domain'), 'user_skill_scores', ['domain'], unique=False)
    op.create_index(op.f('ix_user_skill_scores_user_id'), 'user_skill_scores', ['user_id'], unique=False)
    op.create_table('user_stats',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('problems_solved_total', sa.Integer(), nullable=False),
    sa.Column('problems_solved_easy', sa.Integer(), nullable=False),
    sa.Column('problems_solved_medium', sa.Integer(), nullable=False),
    sa.Column('problems_solved_hard', sa.Integer(), nullable=False),
    sa.Column('total_submissions', sa.Integer(), nullable=False),
    sa.Column('acceptance_rate', sa.Float(), nullable=False),
    sa.Column('interviews_completed', sa.Integer(), nullable=False),
    sa.Column('avg_interview_score', sa.Float(), nullable=False),
    sa.Column('best_interview_score', sa.Integer(), nullable=False),
    sa.Column('current_streak', sa.Integer(), nullable=False),
    sa.Column('longest_streak', sa.Integer(), nullable=False),
    sa.Column('last_activity_date', sa.Date(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_user_stats_user_id'), 'user_stats', ['user_id'], unique=False)
    op.drop_index(op.f('ix_user_profile_replica_email'), table_name='user_profile_replica')
    op.drop_index(op.f('ix_user_profile_replica_id'), table_name='user_profile_replica')
    op.drop_index(op.f('ix_user_profile_replica_username'), table_name='user_profile_replica')
    op.drop_table('user_profile_replica')
    op.add_column('roadmap_items', sa.Column('estimated_minutes', sa.Integer(), nullable=True))
    op.execute("CREATE TYPE contenttype AS ENUM ('dsa', 'system_design', 'mock_interview', 'custom');")
    op.execute("ALTER TABLE roadmap_items ALTER COLUMN content_type TYPE contenttype USING content_type::contenttype;")
    op.create_index('ix_submissions_session_question', 'submissions', ['session_id', 'question_id'], unique=False)
    op.add_column('system_design_questions', sa.Column('domain', sa.String(), nullable=True))
    op.add_column('system_design_questions', sa.Column('role', sa.String(), nullable=True))
    op.create_index(op.f('ix_system_design_questions_domain'), 'system_design_questions', ['domain'], unique=False)
    op.create_index(op.f('ix_system_design_questions_role'), 'system_design_questions', ['role'], unique=False)
    op.create_index('ix_user_problem_status_user_question', 'user_problem_status', ['user_id', 'question_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_problem_status_user_question', table_name='user_problem_status')
    op.drop_index(op.f('ix_system_design_questions_role'), table_name='system_design_questions')
    op.drop_index(op.f('ix_system_design_questions_domain'), table_name='system_design_questions')
    op.drop_column('system_design_questions', 'role')
    op.drop_column('system_design_questions', 'domain')
    op.drop_index('ix_submissions_session_question', table_name='submissions')
    op.alter_column('roadmap_items', 'content_type',
               existing_type=sa.Enum('dsa', 'system_design', 'mock_interview', 'custom', name='contenttype'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_column('roadmap_items', 'estimated_minutes')
    op.create_table('user_profile_replica',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('display_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('user_profile_replica_pkey'))
    )
    op.create_index(op.f('ix_user_profile_replica_username'), 'user_profile_replica', ['username'], unique=True)
    op.create_index(op.f('ix_user_profile_replica_id'), 'user_profile_replica', ['id'], unique=False)
    op.create_index(op.f('ix_user_profile_replica_email'), 'user_profile_replica', ['email'], unique=True)
    op.drop_index(op.f('ix_user_stats_user_id'), table_name='user_stats')
    op.drop_table('user_stats')
    op.drop_index(op.f('ix_user_skill_scores_user_id'), table_name='user_skill_scores')
    op.drop_index(op.f('ix_user_skill_scores_domain'), table_name='user_skill_scores')
    op.drop_table('user_skill_scores')
    op.drop_index(op.f('ix_pm_questions_title'), table_name='pm_questions')
    op.drop_index(op.f('ix_pm_questions_id'), table_name='pm_questions')
    op.drop_index(op.f('ix_pm_questions_category'), table_name='pm_questions')
    op.drop_table('pm_questions')
    op.drop_index(op.f('ix_learning_events_user_id'), table_name='learning_events')
    op.drop_index(op.f('ix_learning_events_event_type'), table_name='learning_events')
    op.drop_table('learning_events')
    op.drop_index(op.f('ix_daily_activity_user_id'), table_name='daily_activity')
    op.drop_table('daily_activity')
    op.drop_index(op.f('ix_behavioral_questions_title'), table_name='behavioral_questions')
    op.drop_index(op.f('ix_behavioral_questions_id'), table_name='behavioral_questions')
    op.drop_index(op.f('ix_behavioral_questions_category'), table_name='behavioral_questions')
    op.drop_table('behavioral_questions')
    op.drop_index(op.f('ix_aiml_questions_id'), table_name='aiml_questions')
    op.drop_table('aiml_questions')
    # ### end Alembic commands ###
